<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCzksirb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCzksirb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCzksirb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCzksirb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCzksirb\appProdProjectContainer([
    'container.build_hash' => 'Czksirb',
    'container.build_id' => '2c776e37',
    'container.build_time' => 1564244415,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCzksirb');
